apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: camerademo
  name: camerademo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: camerademo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: camerademo
    spec:
      containers:
      - image: iris91/images:app-20
        name: camerademo
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: flask-service
spec:
  type: NodePort
  ports:
  - nodePort: 30002
    port: 80
    targetPort: 5003
  selector:
    app: camerademo